### ISSUE TITLE
Docker compose warning for `version`

### ISSUE THREAD

**Issue by l3ender** [workleap/azure-cli-credentials-proxy#92]
**Describe the bug**

When using the docker-compose.yml example provided in the repo, Docker issues a warning for use of `version`:

```console
-> docker compose -f docker-compose.yml up
WARN[0000] /Users/me/repos/myapp/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
```

**To Reproduce**
A simple compose file like this shows the issue:

```yml
version: "3"

services:
  azclicredsproxy:
    image: workleap/azure-cli-credentials-proxy:latest
    ports:
      - "8080:8080"
    volumes:
      - "${HOME}/.azure:/app/.azure/"
```

**Expected behavior**

This appears to be a deprecated field in Docker, so it can be removed.

**Environment (please complete the following information):**
 - OS: macOS 15.4
 - Docker: version 28.0.4, build b8034c0
